SPORT_EVENT_PROB_PREC = 3

SPORT_BET_MARGIN_PREC = 4
SPORT_BET_ODDS_PREC = 4

FC_NAMES_FILE_NAME: tuple[str] = ('.', 'resources', 'english_football_clubs.txt')

HYPOTHESIS_CHECK_N_TIMES = 10**6

PLAYER_ADAVANTAGE = 0.02

ODDS_DISADVANTAGE = 0.02
